language: php
php:
  - 5.6
  - 7.0

env:
  - DB=mysql

install:
  - sudo apt-get update
  - travis_retry sudo apt-get install parallel

before_script:
  - phpenv rehash
  - mysql -e 'create database www_tests_symfony;'
  - mysql -e 'create database www_tests_phpbb;'
  - cp app/config/parameters_travis.yml app/config/parameters.yml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then php composer.phar install -v --dev --ignore-platform-reqs; else php composer.phar install -v --dev; fi"

script:
  - bin/phpunit -c app/
  - find . -path ./vendor -prune -o -type f -name "*.php" | parallel --gnu --keep-order 'php -l {} > /dev/null' || exit 1
  - php app/console lint:twig @AppBundle

notifications:
  email:
    recipients:
      - website@phpbb.com
    on_success: change
    on_failure: change
