imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        assets_version:         2015122401
        #Assets Version format: YYYYMMDDCC (CC for count of number of updates in that day)
        assets_version_format:  %%s?v%%s
        engines:
            - twig
    default_locale:  en
    trusted_proxies: ~
    fragments:       ~
    http_method_override: true
    trusted_hosts:   ~

    session:
        name: "PHPBBWS"
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"

# Twig Configuration
twig:
    debug:              %kernel.debug%
    strict_variables:   %kernel.debug%
    globals:
        facebook:
        twitter:
        plus_one:

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:     default
        connections:
            default:
                driver:     %database_driver%
                host:       %database_host%
                port:       %database_port%
                dbname:     %database_name%
                user:       %database_user%
                password:   %database_password%
            phpbb:
                driver:     %phpbb_database_driver%
                host:       %phpbb_database_host%
                port:       %phpbb_database_port%
                dbname:     %phpbb_database_name%
                user:       %phpbb_database_user%
                password:   %phpbb_database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                auto_mapping:     true
                metadata_cache_driver:
                    type: %ormCache%
                    host: %ormCacheHost%
                    port: %ormCachePort%
                    instance_class: %ormCacheInstanceClass%
                query_cache_driver:
                    type: %ormCache%
                    host: %ormCacheHost%
                    port: %ormCachePort%
                    instance_class: %ormCacheInstanceClass%
                result_cache_driver:
                    type: %ormCache%
                    host: %ormCacheHost%
                    port: %ormCachePort%
                    instance_class: %ormCacheInstanceClass%

# Swiftmailer Configuration
swiftmailer:
    transport:      %mailer_transport%
    host:           %mailer_host%
    username:       %mailer_user%
    password:       %mailer_password%
    port:           %mailer_port%
    encryption:     %mailer_encryption%
    auth_mode:      %mailer_auth_mode%
    delivery_address:  %mailer_delivery_address%
    disable_delivery:  %mailer_disable_delivery%
    spool: { type: memory }
