parameters:
#    phpbb_website_interface.example.class: Phpbb\WebsiteInterfaceBundle\Example

services:
#    phpbb_website_interface.example:
#        class: %phpbb_website_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    phpbb.twig.globalvars:
        class: Phpbb\WebsiteInterfaceBundle\Twig\GlobalsExtension
        tags:
            - { name: twig.extension }

    phpbb.utils.gitUpdate:
        class: Phpbb\WebsiteInterfaceBundle\Utilities\GitUpdateScript
        arguments:
            - %kernel.root_dir%
            - @swiftmailer.mailer.default
